modLoader="javafml"
loaderVersion= "${loader_version_range}"

license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/Amronos/${mod_id}/issues"
showAsResourcePack=false

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Create: Addon Compatibility"
updateJSONURL="https://api.modrinth.com/updates/QgrK9rtJ/forge_updates.json"
displayURL="https://modrinth.com/mod/${mod_id}"
logoFile="logo.png"
#credits=""
authors="Amronos"
description="Adds compatibility for and between different create addons."


[dependencies]
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="almostunified"
mandatory=true
versionRange="[${almostunified_version},)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/almost-unified"

[[dependencies.${mod_id}]]
modId="ad_astra"
mandatory=false
versionRange="[1.15.18,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/ad-astra"

[[dependencies.${mod_id}]]
modId="copycats"
mandatory=false
versionRange="[1.3.8+mc.1.20.1-forge,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/copycats"

[[dependencies.${mod_id}]]
modId="create"
mandatory=true
versionRange="${create_version_range}"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/create"

[[dependencies.${mod_id}]]
modId="createaddition"
mandatory=false
versionRange="[1.20.1-1.2.2,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/createaddition"

[[dependencies.${mod_id}]]
modId="create_connected"
mandatory=false
versionRange="[0.8.2-mc1.20.1,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/create-connected"

[[dependencies.${mod_id}]]
modId="create_dd"
mandatory=false
versionRange="[0.1a.Release-Early-Dev,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/create-dreams-and-desires"

[[dependencies.${mod_id}]]
modId="createdieselgenerators"
mandatory=false
versionRange="[${createdieselgenerators_version},)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/create-diesel-generators"

[[dependencies.${mod_id}]]
modId="createutilities"
mandatory=false
versionRange="[0.3.0,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/create-utilities"

[[dependencies.${mod_id}]]
modId="destroy"
mandatory=false
versionRange="[0.1.0-snapshot-6,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/destroy"

[[dependencies.${mod_id}]]
modId="garnished"
mandatory=false
versionRange="[1.8.3,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/create-garnished"

[[dependencies.${mod_id}]]
modId="jei"
mandatory=false
versionRange="[${jei_version},)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="pneumaticcraft"
mandatory=false
versionRange="[6.0.14,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/pneumaticcraft-repressurized"

[[dependencies.${mod_id}]]
modId="railways"
mandatory=false
versionRange="[1.6.3,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/create-steam-n-rails"

[[dependencies.${mod_id}]]
modId="tfmg"
mandatory=false
versionRange="[${tfmg_version},)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/create-tfmg"
