modLoader="javafml"
loaderVersion= "[47,)"

license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/Amronos/create-addon-compatibility/issues"
showAsResourcePack=false

[[mods]]
modId="createaddoncompatibility"
version="${mod_version}"
displayName="Create: Addon Compatibility"
updateJSONURL="https://api.modrinth.com/updates/QgrK9rtJ/forge_updates.json"
displayURL="https://modrinth.com/mod/create-addon-compatibility"
logoFile="logo.png"
#credits=""
authors="Amronos"
description="Adds compatibility for and between different create addons."


[dependencies]
[[dependencies.createaddoncompatibility]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.createaddoncompatibility]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.createaddoncompatibility]]
modId="almostunified"
mandatory=true
versionRange="[1.20.1-0.9.3,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/almost-unified"

[[dependencies.createaddoncompatibility]]
modId="ad_astra"
mandatory=false
versionRange="[1.15.18,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/ad-astra"

[[dependencies.createaddoncompatibility]]
modId="copycats"
mandatory=false
versionRange="[1.3.8+mc.1.20.1-forge,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/copycats"

[[dependencies.createaddoncompatibility]]
modId="create"
mandatory=true
versionRange="[0.5.1.e,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/create"

[[dependencies.createaddoncompatibility]]
modId="createaddition"
mandatory=false
versionRange="[1.20.1-1.2.2,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/createaddition"

[[dependencies.createaddoncompatibility]]
modId="create_connected"
mandatory=false
versionRange="[0.8.2-mc1.20.1,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/create-connected"

[[dependencies.createaddoncompatibility]]
modId="create_dd"
mandatory=false
versionRange="[0.1a.Release-Early-Dev,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/create-dreams-and-desires"

[[dependencies.createaddoncompatibility]]
modId="createdieselgenerators"
mandatory=false
versionRange="[1.20.1-1.2h,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/create-diesel-generators"

[[dependencies.createaddoncompatibility]]
modId="createutilities"
mandatory=false
versionRange="[0.3.0,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/create-utilities"

[[dependencies.createaddoncompatibility]]
modId="destroy"
mandatory=false
versionRange="[0.1.0,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/destroy"

[[dependencies.createaddoncompatibility]]
modId="garnished"
mandatory=false
versionRange="[1.8.3,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/create-garnished"

[[dependencies.createaddoncompatibility]]
modId="pneumaticcraft"
mandatory=false
versionRange="[6.0.14,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/pneumaticcraft-repressurized"

[[dependencies.createaddoncompatibility]]
modId="railways"
mandatory=false
versionRange="[1.6.3,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/create-steam-n-rails"

[[dependencies.createaddoncompatibility]]
modId="tfmg"
mandatory=false
versionRange="[0.8.0b,)"
ordering="AFTER"
side="BOTH"
referralUrl="https://modrinth.com/mod/create-tfmg"
